export const catList = [
    "Fruit & Vegetables",
    "Meat & Poultry",
    "Fish & Seafood",
    "Dairy",
    "Bakery",
    "Pantry",
    "Frozen",
    "Drinks",
    "Snacks",
    "Sweets",
    "Cereals",
    "Pasta & Rice",
    "Canned Goods",
    "Condiments & Sauces",
    "Spices & Seasonings",
    "Oils & Vinegars",
    "Ready Meals",
    "Household",
    "Cleaning Supplies",
    "Personal Care",
    "Baby Products",
    "Pet Food"
]
